### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by trenkvaz** [amir650/MyCardGame#1]
Hello !

Why is it an error ?

Exception in thread "main" java.lang.RuntimeException: should not reach here in 5 card poker : FULL_HOUSE : hole cards [KING of CLUBS, ACE of SPADES] : community cards [QUEEN of SPADES, KING of HEARTS, KING of SPADES, ACE of DIAMONDS, ACE of CLUBS] vs FULL_HOUSE : hole cards [FIVE of CLUBS, ACE of HEARTS] : community cards [QUEEN of SPADES, KING of HEARTS, KING of SPADES, ACE of DIAMONDS, ACE of CLUBS]
	at com.cardgames.poker.shared.PokerHandComparator.compareFullHouseHands(PokerHandComparator.java:129)
	at com.cardgames.poker.shared.PokerHandComparator.compare(PokerHandComparator.java:38)

That is legal holdem combination 

Regards, Alexey

**Comment by amir650** [comment]
Hi Alexey,

   Did you write a new test case or is that an existing one?  I'd like to
try and reproduce it myself before I draw any conclusions.

best regards,
   Amir
